# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c0cf19f11a4f940061d8d24111d9e742bcd418cf4a538692496c996d98a355b6771c177e31ecf278cfd53350d495dae4a54d8c58aaa4896a234e8c075bba7bd

test:
  secret_key_base: 1d70c772514f34e42ee45d29f8be74d755a21230b3f701a7547bfc89d3adbc38c5f16d49e39ae33fdf27b7c42c5493e440d4b20a2d066fe21c550dc45fa36536

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
